name: Metrics

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  metrics:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: metrics.classic.svg

          user: nickkostov
          orgs: weareplanet

          base: header, repositories
          repositories_affiliations: owner, organization_member
          repositories_visibility: all

          plugin_lines: yes
          plugin_lines_sections: repositories
          plugin_lines_repositories_limit: 10
          plugin_lines_history_limit: 1
